spring:
  application:
    name: Email-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: email-service
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 5050

otel:
  sdk:
    disabled: true
resilience4j:
  ratelimiter:
    instances:
      emailLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s